### ISSUE TITLE
Add a socket sink to result stream

### ISSUE THREAD

**Issue by piankris** [Kristina-Pianykh/iron-maven#3]

**Comment by piankris** [comment]
Solved in https://github.com/Kristina-Pianykh/iron-maven/commit/0a3a412cf9b8d14e9b0863b1297aecf5c1969afe

**Comment by piankris** [comment]
Solved in https://github.com/Kristina-Pianykh/iron-maven/commit/0a3a412cf9b8d14e9b0863b1297aecf5c1969afe

**Comment by Kristina-Pianykh** [comment]
Solved in https://github.com/Kristina-Pianykh/iron-maven/commit/0a3a412cf9b8d14e9b0863b1297aecf5c1969afe

**Comment by piankris** [comment]
Solved in https://github.com/Kristina-Pianykh/iron-maven/commit/0a3a412cf9b8d14e9b0863b1297aecf5c1969afe
