### ISSUE TITLE
Create custom serialization schema

### ISSUE THREAD

**Issue by piankris** [Kristina-Pianykh/iron-maven#5]
The current implementation has limitations and is assumed to be in the same package (or jar) as both the server and the client

**Comment by Kristina-Pianykh** [comment]
using jackson for json (de)serialization. Done in https://github.com/Kristina-Pianykh/iron-maven/commit/921e4273ca6d2e81ace093ffff4520a927ab33c9 , https://github.com/Kristina-Pianykh/iron-maven/commit/7f758a6e8e8c54ca78797d21a24f512e70cc3484 , and https://github.com/Kristina-Pianykh/iron-maven/commit/388dcb3f9f44fe7b104ad7af3f92d0baab4857b4
